# Generated by Django 4.2.3 on 2023-07-14 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherdata',
            name='data',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
