# Generated by Django 4.2.3 on 2023-07-15 16:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_weatherdata_detailtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherdata',
            name='lat',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='lon',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)]),
        ),
    ]
